### ISSUE TITLE
Compatibility with php 8

### ISSUE THREAD

**Issue by vacho** [skilld-labs/skilld_lang_dropdown#11]
Composer throws that this issue isn't compatible with php 8

 Problem 1
    - Root composer.json requires skilld/skilld_lang_dropdown == 1.0.0.0-beta5 -> satisfiable by skilld/skilld_lang_dropdown[1.0-beta5].
    - skilld/skilld_lang_dropdown 1.0-beta5 requires php ^7.1 -> your php version (8.1.12) does not satisfy that requirement.

Wi need to remove this condition on composer.json

**Comment by andypost** [comment]
Also please fix compatibility with D10

**Comment by vacho** [comment]
Done!

**Comment by andypost** [comment]
just remove the line) please

**Comment by andypost** [comment]
Fixed via https://github.com/skilld-labs/skilld_lang_dropdown/commit/295bc54fa0e1b3a7682eb6f58f5541d7fd028c68
